### ISSUE TITLE
Issue adding Prebid v1.12 via SPM

### ISSUE THREAD

**Issue by CTDevelopment** [prebid/prebid-mobile-ios#397] opened 2021-07-19 07:40 UTC
In the v1.12 release support for SPM have been added as far as I can tell. I would like to add the Prebid Swift package to my project by using version 1.12. 

However, it wont let me add it using a specific version/tag (1.12). It seems I can only add it if I use the master branch which im not interested in.

Are there any known issues regarding this? I would assume it would work using the 1.12 release tag 

How to reproduce:
![Screen Shot 2021-07-19 at 09 39 15](https://user-images.githubusercontent.com/86688711/126121493-c37103ca-7a68-40a3-b1ae-3ab1e91c3e6c.png)
![Screen Shot 2021-07-19 at 09 36 16](https://user-images.githubusercontent.com/86688711/126121225-2d7a937c-b1fb-499b-8245-e4ed537bcc3f.png)

**Comment by mit-ank** [comment] 2021-08-19 06:55
Hi @CTDevelopment  - Are you still facing this issue?

**Comment by CTDevelopment** [comment] 2021-08-19 08:01
Hello @mittal-ank, it still seems to be an issue yes. I can only add it if I point the Prebid dependency towards master or the specific commit for the v1.12.0 release. Cant use the version release tag it seems

`.package(name: "PrebidMobile", url: "https://github.com/prebid/prebid-mobile-ios.git", .revision("9958f86804d1aac60908a53c33a4a19c1d1301a4")), `

**Comment by CTDevelopment** [comment] 2021-09-21 12:18
Any update on this @asharmaa @Kowshickkarthick ?

**Comment by YuriyVelichkoPI** [comment] 2021-11-22 13:30
Hi @CTDevelopment, the use with 1.12 should be fixed now. Can you recheck, please?

The current version is 1.12.1 but you should be able to specify any of them 1.12.0 or 1.12.1.  Please, do not use versions below the `1.12.0` with SPM. 

It still has a warning for the unregistered resource which will be fixed later.

**Comment by YuriyVelichkoPI** [comment] 2022-11-17 17:57
The issue is closed since there is no answer. Please let me know if we should reopen.

**Closed by YuriyVelichkoPI** 2022-11-17 17:57 UTC
Labels: duplicate, PMC discussion required
